### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by egor-belikov** [jonathanwiesel/slackus#4] opened 2015-04-19 13:17 UTC
I delpoyed this project on Heroku and wrote all parameters in config, but it doesn't work at all. Can it just log what's happening and isn't working? Please it is important for me, thanks in advance.

**Comment by jonathanwiesel** [comment] 2015-04-20 01:57
Have you confirmed that you have a running and scaled dyno after deploying to Heroku?

I just noticed that after deploying, the application doesn't start because the dynos are at 0, and needs to be scaled manually.

**Comment by jonathanwiesel** [comment] 2015-04-26 22:22
Since there has not been any update on this I'll close it. Reopen if needed

**Closed as completed by jonathanwiesel** 2015-04-26 22:22 UTC
